### ISSUE TITLE
Having trouble implementing a background

### ISSUE THREAD

**Issue by thoma1c** [4site-interactive-studios/Engaging-Networks-Page-Template#2]
Hi!

Thanks for the great EN templates! I seem to have everything up and running except for the page background. I add the text block element with the 'background-settings' class and add the url in the text body but all I see is the url in the block and no background. 

I'm trying to implement something like your donation page with imagery. 

Thanks in advance, 

-T

**Comment by bryancasler** [comment]
Hey T, that's the background swap functionality is offered in our paid template which shares documentation with the free ones released. I'll put it on our agenda to go through and update everything, thanks for pointing this out. We don't want to leave you hanging though, so the attached code blob should help out! You'll probably want to add the JS to the page template right before the closing </body> tag. Let us know if you have any trouble.

`<style>
/* Prepares HTML tag for having a background image applied */
html.has-image body:not(.embedded):not(#en__pagebuilder) {
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;  
    background-attachment: fixed;
    background-repeat: no-repeat;
}
</style>

<script>
/************************************
 * BACKGROUND SETTINGS
 ***********************************/
(function() {  
    window.addEventListener('load', function() {
    
        var backgroundSettings = document.querySelector('.background-settings');

        if (backgroundSettings){

            var html = document.getElementsByTagName( 'html' )[0];
            var body = document.getElementsByTagName( 'body' )[0];
            var backgroundImageURL = document.querySelector('.background-settings p');

            if (backgroundImageURL){
                backgroundImageURL = backgroundImageURL.innerHTML;
                html.classList.add("has-image");    
                body.style.backgroundImage = 'url("' + backgroundImageURL + '")';
                html.classList.add("background-settings-applied");
            }    
    
        }

    });
})();
</script>`
