### ISSUE TITLE
Donate - Other Amount Usability Issue

### ISSUE THREAD

**Issue by PublicRadioCorgi** [4site-interactive-studios/Engaging-Networks-Page-Template#3]
It seems that the 'other amount' donation option doen't work properly. Clicking into the text input does not check the associated radio button, and checking the radio button does not automatically make the text input active. It would seem to have something to do with EN automatically adding a 'hidden' class to the other amount via script, but I can't untangle it. Any suggestions for how to fix this? I haven't found that it works properly on any demo page.

**Comment by bryancasler** [comment]
Hey @PublicRadioCorgi I think we may have changed this on an internal branch of the project because of the exact behavior you described. Coincidentally I'm at the Engaging Networks Toronto Conference right now, so it may take me a few days once I'm back in the office but I'll look to see if I can find you an answer on this.

Can you send a link to a testing page you're using?

**Comment by bryancasler** [comment]
Hey @PublicRadioCorgi did you have an example link you could share?

**Comment by PublicRadioCorgi** [comment]
Sorry, Brian - I have an old email address attached to my GitHub acc6and didn't see your replied to me. I will send you the link once I'm at work.

**Comment by PublicRadioCorgi** [comment]
This is an example page - it's not live yet, still in development: https://us.netdonor.net/page/12991/donate/1?mode=DEMO

Thanks, Bryan!

**Comment by bryancasler** [comment]
Thanks @PublicRadioCorgi, we're slammed with client work for the next couple weeks but wanted to let you know this is on our radar. We are currently reworking the templates in the run-up to Engaging Networks DC conference in October. I expect we'll have something to share around that time.

**Comment by bryancasler** [comment]
Hey @PublicRadioCorgi happy new year! I hope your end of year fundraising went well. Were you able to find a workaround for the issue you were running into?

I wanted to let you know we're launching a completely new page template, written from the ground up with all the lessons learned over the past couple years.
https://github.com/4site-interactive-studios/engrid

If you had anything that was on your wishlist for the old template, I'd love to hear it and I can get it on our development roadmap for the new ones.
